services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: appflowy
      POSTGRES_USER: appflowy
      POSTGRES_PASSWORD: supersecret
    volumes:
      - appflowy_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always

  gotrue:
    image: appflowyinc/gotrue:latest
    restart: always
    ports:
      - "9191:9999"
    environment:
      GOTRUE_SITE_URL: https://appyflow.apogea.pro
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      GOTRUE_DB_DRIVER: postgres
      DATABASE_URL: postgres://appflowy:supersecret@postgres:5432/appflowy?sslmode=disable
      GOTRUE_JWT_SECRET: supersecretkey
      GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
    depends_on:
      - postgres

  appflowy_cloud:
    image: appflowyinc/appflowy_cloud:latest
    restart: always
    environment:
      DATABASE_URL: postgres://appflowy:supersecret@postgres:5432/appflowy?sslmode=disable
      REDIS_URL: redis://redis:6379
      AUTH_URL: http://gotrue:9999
    depends_on:
      - postgres
      - redis
      - gotrue

  appflowy_worker:
    image: appflowyinc/appflowy_worker:latest
    restart: always
    environment:
      DATABASE_URL: postgres://appflowy:supersecret@postgres:5432/appflowy?sslmode_



