version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: appflowy_postgres
    restart: always
    environment:
      POSTGRES_DB: appflowy
      POSTGRES_USER: appflowy
      POSTGRES_PASSWORD: supersecret
    volumes:
      - appflowy_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: appflowy_redis
    restart: always

  gotrue:
    image: appflowyinc/gotrue:latest
    container_name: appflowy_auth
    restart: always
    ports:
      - "9999:9999"
    environment:
      GOTRUE_SITE_URL: http://localhost:8080
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      GOTRUE_DB_DRIVER: postgres
      DATABASE_URL: postgres://appflowy:supersecret@postgres:5432/appflowy?sslmode=disable
      GOTRUE_JWT_SECRET: supersecretkey
      GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
    depends_on:
      - postgres

  appflowy_cloud:
    image: appflowyinc/appflowy_cloud:latest
    container_name: appflowy_cloud
    restart: always
    environment:
      DATABASE_URL: postgres://appflowy:supersecret@postgres:5432/appflowy?sslmode=disable
      REDIS_URL: redis://redis:6379
      AUTH_URL: http://gotrue:9999
    depends_on:
      - postgres
      - redis
      - gotrue

  appflowy_worker:
    image: appflowyinc/appflowy_worker:latest
    container_name: appflowy_worker
    restart: always
    environment:
      DATABASE_URL: postgres://appflowy:supersecret@postgres:5432/appflowy?sslmode=disable
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
      - postgres

  appflowy_web:
    image: appflowyinc/appflowy_web:latest
    container_name: appflowy_web
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - appflowy_cloud

volumes:
  appflowy_pg_data:
